"""Final DoomWalk mark: perspective depth ticks in Frost (round 6, 3).

Writes the SVG masters here, and the Android launcher, notification and
splash resources. Tick geometry matches lib/ui/logo.dart."""
import os

NAVY, FROST, WHITE, DEEP, ICE = '#0E4166', '#E2F0F8', '#FFFFFF', '#07131F', '#CFE6F4'
RES = os.path.join(os.path.dirname(__file__), '../../../android/app/src/main/res')


def ticks(small=False):
    out = []
    if small:
        y = 30
        for w, h in zip((84, 132, 180, 224), (26, 32, 38, 44)):
            out.append((y, w, h)); y += h + 16
        return out
    y = 40
    for i in range(6):
        w, h = 56 + i * 28, 12 + i * 4
        out.append((y, w, h)); y += h + 5 + i * 2
    return out


def alpha(i, n):
    return 0.32 + 0.68 * (i / (n - 1))


def svg_ticks(color, small=False):
    t = ticks(small)
    return ''.join(f'<rect x="{128 - w / 2:g}" y="{y:g}" width="{w:g}" height="{h:g}" rx="{h / 2:g}" fill="{color}" '
                   f'fill-opacity="{alpha(i, len(t)):.2f}"/>' for i, (y, w, h) in enumerate(t))


SHADOW = ('<filter id="shadow" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur in="SourceAlpha" stdDeviation="4"/>'
          '<feOffset dy="4"/><feComponentTransfer><feFuncA type="linear" slope="0.22"/></feComponentTransfer>'
          '<feMerge><feMergeNode/><feMergeNode in="SourceGraphic"/></feMerge></filter>')


def icon(top, bottom, glyph, shadow):
    defs = (f'<linearGradient id="bg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="{top}"/>'
            f'<stop offset="1" stop-color="{bottom}"/></linearGradient>' + (SHADOW if shadow else ''))
    g = f'<g filter="url(#shadow)">{svg_ticks(glyph)}</g>' if shadow else svg_ticks(glyph)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" width="256" height="256" role="img" '
            f'aria-labelledby="title">\n  <title id="title">DoomWalk</title>\n  <defs>{defs}</defs>\n'
            f'  <rect width="256" height="256" fill="url(#bg)"/>\n  {g}\n</svg>\n')


def symbol(color, small=False):
    t = ticks(small)
    top, bottom = t[0][0], t[-1][0] + t[-1][2]
    w = max(x[1] for x in t)
    vb = f'{128 - w / 2:g} {top:g} {w:g} {bottom - top:g}'
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" role="img" aria-labelledby="title">\n'
            f'  <title id="title">DoomWalk</title>\n  {svg_ticks(color, small)}\n</svg>\n')


files = {
    'icon.svg': icon(WHITE, FROST, NAVY, True),            # app icon / store, with the soft shadow
    'icon-flat.svg': icon(WHITE, FROST, NAVY, False),      # production master, no filter
    'icon-dark.svg': icon('#123A5C', DEEP, ICE, True),     # the mark inverted, for dark contexts
    'symbol.svg': symbol(NAVY),
    'symbol-white.svg': symbol(WHITE),
    'symbol-black.svg': symbol('#000000'),
    'symbol-small.svg': symbol(NAVY, small=True),          # four ticks, for 16-24 px
}
for name, body in files.items():
    open(name, 'w').write(body)


# ---------------------------------------------------------------- Android

def vector(color, size_dp, viewport, small, scale, dx, dy):
    t = ticks(small)
    paths = ''
    for i, (y, w, h) in enumerate(t):
        x0, y0, ww, hh, r = (128 - w / 2) * scale + dx, y * scale + dy, w * scale, h * scale, h / 2 * scale
        d = (f'M{x0 + r:.2f},{y0:.2f} H{x0 + ww - r:.2f} A{r:.2f},{r:.2f} 0 0 1 {x0 + ww - r:.2f},{y0 + hh:.2f} '
             f'H{x0 + r:.2f} A{r:.2f},{r:.2f} 0 0 1 {x0 + r:.2f},{y0:.2f} Z')
        paths += f'\n    <path android:fillColor="{color}" android:fillAlpha="{alpha(i, len(t)):.2f}" android:pathData="{d}" />'
    return (f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size_dp}dp" android:height="{size_dp}dp"\n'
            f'    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">{paths}\n</vector>\n')


# Adaptive icon: 108 dp canvas, keep the mark inside the 66 dp safe circle.
# Lifted 3 dp: the mark is bottom-heavy, and its widest tick's ends must stay
# inside the 66 dp safe circle (checked below).
k = 0.27
LIFT = 3
cx_mark, cy_mark = 128, (40 + 217) / 2
fg = vector('#FF0E4166', 108, 108, False, k, 54 - cx_mark * k, 54 - cy_mark * k - LIFT)
open(f'{RES}/drawable/ic_launcher_foreground.xml', 'w').write(
    '<!-- DoomWalk mark (docs/logo/final). Generated by docs/logo/final/build.py. -->\n' + fg)
import math
far = max(math.hypot((w / 2 - h / 2) * k, (y + h / 2 - cy_mark) * k - LIFT) + h / 2 * k for y, w, h in ticks())
assert far <= 33, f'mark leaves the safe zone: {far:.1f} dp'
print(f'adaptive mark reaches {far:.1f} dp from centre (safe zone 33)')
# Themed icons tint this layer, so only its shape and alpha matter.
open(f'{RES}/drawable/ic_launcher_monochrome.xml', 'w').write(
    '<!-- Themed-icon layer. Generated by docs/logo/final/build.py. -->\n' + vector('#FFFFFFFF', 108, 108, False, k, 54 - cx_mark * k, 54 - cy_mark * k - LIFT))
open(f'{RES}/drawable/ic_launcher_background.xml', 'w').write(
    '<?xml version="1.0" encoding="utf-8"?>\n<!-- Frost: white to frost blue, top to bottom. -->\n'
    '<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">\n'
    '    <gradient android:angle="270" android:startColor="#FFFFFFFF" android:endColor="#FFE2F0F8" />\n</shape>\n')
open(f'{RES}/mipmap-anydpi-v26/ic_launcher.xml', 'w').write(
    '<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
    '    <background android:drawable="@drawable/ic_launcher_background" />\n'
    '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
    '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n</adaptive-icon>\n')
# Status-bar icon: white silhouette, four ticks so it reads at 24 dp.
ks = 24 / 256 * 0.92
open(f'{RES}/drawable/ic_stat_ticks.xml', 'w').write(
    '<!-- Notification icon. Generated by docs/logo/final/build.py. -->\n' +
    vector('#FFFFFFFF', 24, 24, True, ks, 12 - 128 * ks, 12 - 124 * ks))
